[package]
name = "exporter"
version = "0.0.7"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.31", features = ["derive"] }
diesel = { version = "2.2.8", features = ["postgres"] }
tokio = { version = "1.44.0", features = ["full"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
code-api = { path = "../code_api" }
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
