[package]
name = "nix_vscode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.188", features = ["derive", "alloc", "rc"] }
serde_json = "1.0.105"
toml = "0.7.6"
tokio = { version = "1.32.0", features = ["full"] }
log = "0.4.20"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "std"] }
semver = "1.0.18"
bitflags = { version = "2.4.0", features = ["serde", "std"] }
reqwest = { version = "0.11.20", default_features = false, features = [
  "rustls-tls",
  "gzip",
] }
minijinja = "1.0.7"
clap = { version = "4.4.2", features = ["derive"] }
futures = "0.3.28"
