[package]
name = "nix4vscode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive", "alloc", "rc"] }
serde_json = "1.0.106"
toml = "0.7.8"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "std"] }
semver = "1.0.18"
bitflags = { version = "2.4.0", features = ["serde", "std"] }
reqwest = { version = "0.11.25", default_features = false, features = ["rustls-tls", "gzip", "json"] }
minijinja = "1.0.7"
clap = { version = "4.4.2", features = ["derive"] }
futures = "0.3.28"
anyhow = "1.0.80"
nixpkgs-fmt = "1.3.0"
redb = "1.5.0"
thiserror = "1.0.48"
openvsx = { path = "./openvsx" }
lazy-regex = "3.1.0"
chrono = "0.4.34"
derive = { path = "./derive" }
lazy_static = "1.4.0"
