[package]
name = "nix4vscode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive", "alloc", "rc"] }
serde_json = "1.0.114"
toml = "0.8.10"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "std"] }
semver = "1.0.22"
bitflags = { version = "2.4.2", features = ["serde", "std"] }
reqwest = { version = "0.11.25", default_features = false, features = ["rustls-tls", "gzip", "json"] }
minijinja = { version = "1.0.12", features = ["loader"] }
clap = { version = "4.5.2", features = ["derive"] }
futures = "0.3.30"
anyhow = "1.0.80"
nixpkgs-fmt = "1.3.0"
redb = "1.5.0"
thiserror = "1.0.57"
openvsx = { path = "./openvsx" }
lazy-regex = "3.1.0"
chrono = "0.4.35"
derive = { path = "./derive" }
lazy_static = "1.4.0"
