[package]
name = "nix_vscode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.188", features = ["derive", "alloc", "rc"] }
serde_json = "1.0.105"
toml = "0.7.6"
hyper = { version = "1.0.0-rc.4", features = ["full"] }
tokio = { version = "1.32.0", features = ["full"] }
log = "0.4.20"
tracing = "0.1.37"
semver = "1.0.18"
bitflags = { version = "2.4.0", features = ["serde", "std"] }
