[package]
name = "nix4vscode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive", "alloc", "rc"] }
serde_json = "1.0.117"
toml = "0.8.14"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "std"] }
semver = "1.0.23"
bitflags = { version = "2.5.0", features = ["serde", "std"] }
reqwest = { version = "0.12.5", default_features = false, features = [
    "rustls-tls",
    "gzip",
    "json",
] }
minijinja = { version = "2.0.2", features = ["loader"] }
clap = { version = "4.5.7", features = ["derive"] }
futures = "0.3.30"
anyhow = "1.0.86"
nixpkgs-fmt = "1.3.0"
redb = "2.1.1"
thiserror = "1.0.61"
lazy-regex = "3.1.0"
chrono = "0.4.38"
derive = { path = "./derive" }
lazy_static = "1.5.0"
rust-embed = "8.4.0"
