[package]
name = "nix4vscode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive", "alloc", "rc"] }
serde_json = "1.0.115"
toml = "0.8.12"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "std"] }
semver = "1.0.22"
bitflags = { version = "2.5.0", features = ["serde", "std"] }
reqwest = { version = "0.12.3", default_features = false, features = [
    "rustls-tls",
    "gzip",
    "json",
] }
minijinja = { version = "1.0.17", features = ["loader"] }
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
anyhow = "1.0.81"
nixpkgs-fmt = "1.3.0"
redb = "2.0.0"
thiserror = "1.0.58"
openvsx = { path = "./openvsx" }
lazy-regex = "3.1.0"
chrono = "0.4.37"
derive = { path = "./derive" }
lazy_static = "1.4.0"
rust-embed = "8.3.0"
