vscode_version = "1.84.2"

extensions = [
  "ms-vscode.cpptools",
  "ms-python.debugpy",
  "42crunch.vscode-openapi",
  "aaron-bond.better-comments",
  "adamhartford.vscode-base64",
  "adpyke.codesnap",
  "ahmadalli.vscode-nginx-conf",
  "AmazonWebServices.aws-toolkit-vscode",
  "jnoortheen.nix-ide",
  "bibhasdn.unique-lines",
  "bradlc.vscode-tailwindcss",
  "BriteSnow.vscode-toggle-quotes",
  "charliermarsh.ruff",
  "Chouzz.vscode-better-align",
  "christian-kohler.path-intellisense",
  "DavidAnson.vscode-markdownlint",
  "davidnussio.vscode-jq-playground",
  "donjayamanne.githistory",
  "dustypomerleau.rust-syntax",
  "eamodio.gitlens",
  "eriklynd.json-tools",
  "esbenp.prettier-vscode",
  "formulahendry.auto-close-tag",
  "formulahendry.auto-rename-tag",
  "foxundermoon.shell-format",
  "golang.Go",
  "Gruntfuggly.todo-tree",
  "gurumukhi.selected-lines-count",
  "HaaLeo.timing",
  "HashiCorp.terraform",
  "hilleer.yaml-plus-json",
  "IBM.output-colorizer",
  "jq-syntax-highlighting.jq-syntax-highlighting",
  "jtcontreras90.yaml-path-extractor",
  "kokakiwi.vscode-just",
  "LemurDaniel.terraform-quick-docs",
  "Lokalise.i18n-ally",
  "lunuan.kubernetes-templates",
  "maxird.jinja-fold",
  "mechatroner.rainbow-csv",
  "mgtrrz.terraform-completer",
  "mikestead.dotenv",
  "MisterJ.vue-volar-extention-pack",
  "monosans.djlint",
  "moshfeu.compare-folders",
  "mousavian.ssh-config-syntax-highlighter",
  "ms-azuretools.vscode-docker",
  "ms-kubernetes-tools.vscode-kubernetes-tools",
  "ms-python.black-formatter",
  "ms-python.python",
  "ms-python.vscode-pylance",
  "ms-vscode.makefile-tools",
  "ms-vscode.vscode-typescript-next",
  "MS-vsliveshare.vsliveshare",
  "Yunduo.color-highlight-css-color-4",
  "nidu.copy-json-path",
  "noxiz.jinja-snippets",
  "oderwat.indent-rainbow",
  "phil9909.ytt-lint",
  "PKief.material-icon-theme",
  "pucelle.run-on-save",
  "qcz.text-power-tools",
  "quicktype.quicktype",
  "redhat.vscode-yaml",
  "reduckted.vscode-gitweblinks",
  "richie5um2.vscode-sort-json",
  "rubbersheep.gi",
  "rust-lang.rust-analyzer",
  "ryu1kn.partial-diff",
  "ryu1kn.text-marker",
  "samuelcolvin.jinjahtml",
  "serayuzgur.crates",
  "shd101wyy.markdown-preview-enhanced",
  "sibiraj-s.vscode-scss-formatter",
  "TakumiI.markdowntable",
  "tamasfe.even-better-toml",
  "tfsec.tfsec",
  "TheNuProjectContributors.vscode-nushell-lang",
  "Tim-Koehler.helm-intellisense",
  "tombonnike.vscode-status-bar-format-toggle",
  "tommasov.hosts",
  "tomoki1207.pdf",
  "truman.autocomplate-shell",
  "Tyriar.sort-lines",
  "usernamehw.errorlens",
  "VisualStudioExptTeam.intellicode-api-usage-examples",
  "VisualStudioExptTeam.vscodeintellicode",
  "VisualStudioExptTeam.vscodeintellicode-completions",
  "Vue.volar",
  "Vue.vscode-typescript-vue-plugin",
  "wholroyd.jinja",
  "WyattFerguson.jinja2-snippet-kit",
  "yatki.vscode-surround",
  "yzhang.markdown-all-in-one",
  "GitLab.gitlab-workflow",
  "zhuangtongfa.Material-theme",
  "JohnnyMorganz.stylua",
  "Grafana.vscode-jsonnet",
  "vadimcn.vscode-lldb",
  "debugpy.ms-python",
]
