name: "gate"

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make fonts-noto-cjk fonts-noto-cjk-extra yarnpkg
          version: 1.0
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git/db/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
          key: cargo_cache-${{ runner.os }}
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: CfirTsabari/actions-rs-toolchain@v1
      - name: Build Packages
        run: |
          export RUST_LOG=DEBUG
          pip install pre-commit
          yarnpkg global add @taplo/cli
          cargo clippy -- -Dwarnings
          cargo test
          cargo run -- config.toml -o example/vscode_plugins.nix
          cat example/vscode_plugins.nix
          cd example && nix develop --build
