name: "nightly"

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: "0 5 * * 1-5"

permissions:
  contents: write

jobs:
  nightly_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo +nightly build
